openapi: 3.0.3
info:
  title: Sam's Jobs API
  version: 0.0.0
  description: "Hello #typescriptiication"
  license:
    name: SEEK
    url: http://example.com
servers:
  - url: http://example.com/staging
    description: Staging
  - url: http://example.com/prod
    description: Prod
paths:
  /jobs:
    post:
      operationId: createJob
      description: Create a job to be displayed on SEEK
      summary: Create a Job
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hirerId:
                  type: string
                title:
                  type: string
              required:
                - hirerId
                - title
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  hirerId:
                    type: string
                  title:
                    type: string
                  id:
                    type: string
                    format: uuid
                required:
                  - hirerId
                  - title
                  - id
        "400":
          description: Bad Request
components:
  securitySchemes:
    s2sauth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: An s2s token issued by an allow listed consumer
