info:
  title: Sam's Jobs API
  version: 0.0.0
  description: "Hello #typescriptiication"
  license:
    name: SEEK
    url: http://example.com
servers:
  - url: http://example.com/staging
    description: Staging
  - url: http://example.com/prod
    description: Prod
openapi: 3.0.3
components:
  securitySchemes:
    s2sauth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: An s2s token issued by an allow listed consumer
  schemas:
    hirerDetails:
      type: object
      properties:
        id:
          type: string
          description: SEEK ID
          example: "60002023"
      required:
        - id
      description: Hirer Details
  parameters: {}
paths:
  /jobs:
    post:
      operationId: createJob
      description: Create a job to be displayed on SEEK
      summary: Create a Job
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hirer:
                  $ref: "#/components/schemas/hirerDetails"
                title:
                  type: string
                  maxLength: 100
                  description: Name of job visible in job search
                  example: "#typescriptification host"
                metadata:
                  type: object
                  properties:
                    performanceTier:
                      type: string
                      enum:
                        - A
                        - B
                        - C
                      description: Performance of the ad 3
                      example: A
                      deprecated: true
                  required:
                    - performanceTier
                  description: Metadata
              required:
                - hirer
                - title
                - metadata
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  hirer:
                    $ref: "#/components/schemas/hirerDetails"
                required:
                  - id
                  - hirer
        "400":
          description: Bad Request
